name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: 'ios'

    timeout-minutes: 5

    steps:
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          generate_release_notes: true
